In [1]:
import numpy as np

In [2]:
arr = np.array([12,34,56,7])

In [3]:
print(arr.data)

In [4]:
print(arr.strides)

(8,)


In [5]:
arr2 = np.array([34,45])
arr2.strides

(8,)

In [6]:
print(np.empty((3,2)))
print(np.empty_like(arr2))

[[1.4482998e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]
[-9093133594791772939                16280]


In [7]:
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

[10 15 20]


In [8]:
evenSpacedArray2 = np.linspace(0,2,9)

In [9]:
print(evenSpacedArray2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [10]:
np.savetxt('dataout.out',evenSpacedArray2,delimiter=',')

In [11]:
arr2d = np.arange(1,13).reshape(4,3)

In [12]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr2d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [14]:
y = (arr2d >= 5)

In [15]:
type(y)

numpy.ndarray

In [16]:
arr2d[y]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
y

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# PANDAS

In [18]:
import numpy as np
import pandas as pd
print("Pandas Version:", pd.__version__)

Pandas Version: 1.5.3


In [19]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [20]:
series = pd.Series([2, 3, 7, 11, 13, 17, 19, 23])
print(series)

0     2
1     3
2     7
3    11
4    13
5    17
6    19
7    23
dtype: int64


In [21]:
# Creating dataframe from Series
series_df = pd.DataFrame({
'A': range(1, 5),
'B': pd.Timestamp('20190526'),
'C': pd.Series(5, index=list(range(4)), dtype='float64'),
'D': np.array([3] * 4, dtype='int64'),
'E': pd.Categorical(["Depression", "Social Anxiety", "BipolarDisorder", "Eating Disorder"]),
'F': 'Mental health',
'G': 'is challenging'
})
print(series_df)

   A          B    C  D                E              F               G
0  1 2019-05-26  5.0  3       Depression  Mental health  is challenging
1  2 2019-05-26  5.0  3   Social Anxiety  Mental health  is challenging
2  3 2019-05-26  5.0  3  BipolarDisorder  Mental health  is challenging
3  4 2019-05-26  5.0  3  Eating Disorder  Mental health  is challenging


In [22]:
# pd.Series(5, index=list(range(4)), dtype='float64')
pd.Series(5, dtype='float64')

0    5.0
dtype: float64

### let's load a dataset from an external source into a pandas DataFrame. After that, let's see the first 10 entries:

In [23]:
columns = ['age', 'workclass', 'fnlwgt', 'education','education_num','marital_status', 'occupation', 'relationship', 'ethnicity','gender','capital_gain','capital_loss','hours_per_week','country_of_origin','income']

In [24]:
# df3=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=columns)
# df3.to_csv('From EDA')

In [25]:
df=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=columns).iloc[0:12]
df.head(10)

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           marital_status          occupation    relationship ethnicity  \
0           Never-married        Adm-clerical   Not-in-family     White   
1      Married-civ-spouse     Exec-managerial         Husband     White   
2                Divorced   Handlers-cleaners   Not-in-family     White   
3      Married-civ-spouse   Handlers-cleaners         Husband     Black   
4      Married-civ-spouse      Prof-specialty            Wife     Black   
5      Married-civ-spouse     Exec-managerial            Wife     White   
6   Married-spouse-absent       Other-service   Not-in-family     Black   
7      Married-civ-spouse     Exec-managerial         Husband     White   
8           Never-married      Prof-specialty   Not-in-family     White   
9      Married-civ-spouse     Exec-managerial         Husband     White   

    gender  capital_gain  capital_loss  hours_per_week country_of_origin  \
0     Male          2174             0              40     United-States   
1     Male             0             0              13     United-States   
2     Male             0             0              40     United-States   
3     Male             0             0              40     United-States   
4   Female             0             0              40              Cuba   
5   Female             0             0              40     United-States   
6   Female             0             0              16           Jamaica   
7     Male             0             0              45     United-States   
8   Female         14084             0              50     United-States   
9     Male          5178             0              40     United-States   

   income  
0   <=50K  
1   <=50K  
2   <=50K  
3   <=50K  
4   <=50K  
5   <=50K  
6   <=50K  
7    >50K  
8    >50K  
9    >50K

### Let's combine NumPy and pandas to create a dataframe as follows:

In [26]:
np.random.seed(24)
dFrame = pd.DataFrame({'F': np.linspace(1, 10, 10)})

In [27]:
dFrame

F
0   1.0
1   2.0
2   3.0
3   4.0
4   5.0
5   6.0
6   7.0
7   8.0
8   9.0
9  10.0

In [28]:
# np.random.randn(10, 5)

In [29]:
dFrame = pd.concat([df, pd.DataFrame(np.random.randn(10, 5),columns=list('EDCBA'))],axis=1)

In [30]:
dFrame

age          workclass  fnlwgt      education  education_num  \
0    39          State-gov   77516      Bachelors             13   
1    50   Self-emp-not-inc   83311      Bachelors             13   
2    38            Private  215646        HS-grad              9   
3    53            Private  234721           11th              7   
4    28            Private  338409      Bachelors             13   
5    37            Private  284582        Masters             14   
6    49            Private  160187            9th              5   
7    52   Self-emp-not-inc  209642        HS-grad              9   
8    31            Private   45781        Masters             14   
9    42            Private  159449      Bachelors             13   
10   37            Private  280464   Some-college             10   
11   30          State-gov  141297      Bachelors             13   

            marital_status          occupation    relationship  \
0            Never-married        Adm-clerical   Not-in-family   
1       Married-civ-spouse     Exec-managerial         Husband   
2                 Divorced   Handlers-cleaners   Not-in-family   
3       Married-civ-spouse   Handlers-cleaners         Husband   
4       Married-civ-spouse      Prof-specialty            Wife   
5       Married-civ-spouse     Exec-managerial            Wife   
6    Married-spouse-absent       Other-service   Not-in-family   
7       Married-civ-spouse     Exec-managerial         Husband   
8            Never-married      Prof-specialty   Not-in-family   
9       Married-civ-spouse     Exec-managerial         Husband   
10      Married-civ-spouse     Exec-managerial         Husband   
11      Married-civ-spouse      Prof-specialty         Husband   

              ethnicity   gender  capital_gain  capital_loss  hours_per_week  \
0                 White     Male          2174             0              40   
1                 White     Male             0             0              13   
2                 White     Male             0             0              40   
3                 Black     Male             0             0              40   
4                 Black   Female             0             0              40   
5                 White   Female             0             0              40   
6                 Black   Female             0             0              16   
7                 White     Male             0             0              45   
8                 White   Female         14084             0              50   
9                 White     Male          5178             0              40   
10                Black     Male             0             0              80   
11   Asian-Pac-Islander     Male             0             0              40   

   country_of_origin  income         E         D         C         B         A  
0      United-States   <=50K  1.329212 -0.770033 -0.316280 -0.990810 -1.070816  
1      United-States   <=50K -1.438713  0.564417  0.295722 -1.626404  0.219565  
2      United-States   <=50K  0.678805  1.889273  0.961538  0.104011 -0.481165  
3      United-States   <=50K  0.850229  1.453425  1.057737  0.165562  0.515018  
4               Cuba   <=50K -1.336936  0.562861  1.392855 -0.063328  0.121668  
5      United-States   <=50K  1.207603 -0.002040  1.627796  0.354493  1.037528  
6            Jamaica   <=50K -0.385684  0.519818  1.686583 -1.325963  1.428984  
7      United-States    >50K -2.089354 -0.129820  0.631523 -0.586538  0.290720  
8      United-States    >50K  1.264103  0.290035 -1.970288  0.803906  1.030550  
9      United-States    >50K  0.118098 -0.021853  0.046841 -1.628753 -0.392361  
10     United-States    >50K       NaN       NaN       NaN       NaN       NaN  
11             India    >50K       NaN       NaN       NaN       NaN       NaN

In [31]:
dFrame['A']

0    -1.070816
1     0.219565
2    -0.481165
3     0.515018
4     0.121668
5     1.037528
6     1.428984
7     0.290720
8     1.030550
9    -0.392361
10         NaN
11         NaN
Name: A, dtype: float64

In [32]:
dFrame.iloc[0,2]

77516

In [33]:
dFrame.loc[0]

age                              39
workclass                 State-gov
fnlwgt                        77516
education                 Bachelors
education_num                    13
marital_status        Never-married
occupation             Adm-clerical
relationship          Not-in-family
ethnicity                     White
gender                         Male
capital_gain                   2174
capital_loss                      0
hours_per_week                   40
country_of_origin     United-States
income                        <=50K
E                          1.329212
D                         -0.770033
C                          -0.31628
B                          -0.99081
A                         -1.070816
Name: 0, dtype: object

### styling the data

In [34]:
def colorNegativeValueToRed(value):
    if value < 0:
        color = 'red'
    elif value > 0:
        color = 'black'
    else:
        color = 'green'
    return 'color: %s' % color

In [35]:
colorNegativeValueToRed(1.33)

'color: black'

In [53]:
dFrame.style.applymap(colorNegativeValueToRed,subset=['A','B','C','D','E'])

In [37]:
s=dFrame.style.applymap(colorNegativeValueToRed,subset=['A','B','C','D','E'])

### Highlight Min and Max values 

In [38]:
abc = np.arange(1,12)

In [39]:
abc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
[e if e!=4 else '' for e in abc if e %2 == 0]

[2, '', 6, 8, 10]

In [41]:
def highlight(s):
    isMax = s == s.max()
    
    return ['background-color: orange' if v else '' for v in isMax]
def highlightMin(s):
    isMin = s == s.min()
    return ['background-color: green' if v else '' for v in isMin]

In [42]:
dFrame.style.apply(highlight).apply(highlightMin).highlight_null(null_color='red')

/tmp/ipykernel_39739/889047746.py:1: FutureWarning: `null_color` is deprecated: use `color` instead
  dFrame.style.apply(highlight).apply(highlightMin).highlight_null(null_color='red')


# Seaborn

In [43]:
import seaborn as sns
colorMap = sns.light_palette("pink", as_cmap=True)